/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;
//import sm.sound.SMPlayer;

/**
 *Clase VentanaInternaReproductor, su constructor recibe un File
 * @author javi
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaReproductor
     */
    SMClipPlayer player;
    /**
     * Constructor
     * @param f File
     */
    public VentanaInternaReproductor(File f) {
        initComponents();
        player = new SMClipPlayer(f);
        player.setLineListener(new ManejadorAudio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botonPlayPause = new javax.swing.JToggleButton();
        botonStop = new javax.swing.JToggleButton();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(170, 95));
        addInternalFrameListener(formListener);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 1));

        buttonGroup1.add(botonPlayPause);
        botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48.png"))); // NOI18N
        botonPlayPause.setToolTipText("Play");
        botonPlayPause.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48.png"))); // NOI18N
        botonPlayPause.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayDisabled_48x48.png"))); // NOI18N
        botonPlayPause.addActionListener(formListener);
        getContentPane().add(botonPlayPause);

        buttonGroup1.add(botonStop);
        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48.png"))); // NOI18N
        botonStop.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopPressedBlue_48x48.png"))); // NOI18N
        botonStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48.png"))); // NOI18N
        botonStop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48.png"))); // NOI18N
        botonStop.addActionListener(formListener);
        getContentPane().add(botonStop);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, javax.swing.event.InternalFrameListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == botonPlayPause) {
                VentanaInternaReproductor.this.botonPlayPauseActionPerformed(evt);
            }
            else if (evt.getSource() == botonStop) {
                VentanaInternaReproductor.this.botonStopActionPerformed(evt);
            }
        }

        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            if (evt.getSource() == VentanaInternaReproductor.this) {
                VentanaInternaReproductor.this.formInternalFrameClosing(evt);
            }
        }

        public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents
/**
 * Recoge evento e inicia reproduccion
 * @param evt ActionEvent
 */
    private void botonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayPauseActionPerformed
        if(player!=null) player.play();
    }//GEN-LAST:event_botonPlayPauseActionPerformed

    /**
     * Recoge evento y para o corta reproduccion
     * @param evt ActionEvent
     */
    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
       if(player!=null) player.stop();
    }//GEN-LAST:event_botonStopActionPerformed

/**
 * Recoge evento de cerrar ventana y para reproduccion
 * @param evt InternalFrameEvent
 */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
       if (this.player != null) {
      this.player.stop();
    }
    }//GEN-LAST:event_formInternalFrameClosing
/**
 * Clase manejadora de eventos, usado para actualizar botones
 */
    class ManejadorAudio implements LineListener {
@Override

public void update(LineEvent event) {
    if (event.getType() == LineEvent.Type.START) {
        //VentanaInternaReproductor.this.botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayDisabled_48x48.png")));
        //VentanaInternaReproductor.this.botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48")));
       // if(player!=null) player.play();
        //botonPlayPause.setEnabled(false);
       // botonStop.setEnabled(true);
    }
    if (event.getType() == LineEvent.Type.STOP) {
        //VentanaInternaReproductor.this.botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48")));
        //VentanaInternaReproductor.this.botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48")));
       // if(player!=null) player.stop();
         VentanaInternaReproductor.this.botonStop.setSelected(true);
        //botonPlayPause.setEnabled(true);
        //botonStop.setEnabled(false);
     }
    if (event.getType() == LineEvent.Type.CLOSE) {
       if (player != null) {
            player.stop();
    }
    if(event.getType() == LineEvent.Type.OPEN){
        //botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48")));
        //botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48")));
       // botonPlayPause.setEnabled(true);
        //botonStop.setEnabled(false);
        VentanaInternaReproductor.this.botonStop.setSelected(true);
    }
}

        
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonPlayPause;
    private javax.swing.JToggleButton botonStop;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
