/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;

/**
 *Clase VentanaInternaReproductor, su constructor recibe un File
 * @author javi
 */
//public class VentanaInternaReproductorHebra extends javax.swing.JInternalFrame {
public class VentanaInternaReproductorHebra extends javax.swing.JInternalFrame implements Runnable{

    /**
     * Creates new form VentanaInternaReproductorHebra
     */
   
    
    public VentanaInternaReproductorHebra() {
        initComponents();
    }
    
    SMClipPlayer player;
    Thread runner= null;
//Hilo runner=null;
    /**
     * Constructor
     * @param f File
     */
    public VentanaInternaReproductorHebra(File f) {
        initComponents();
        player = new SMClipPlayer(f);
        player.setLineListener(new VentanaInternaReproductorHebra.ManejadorAudio());
        
    }
    
  /**
   * Clase Hilo que implementa la interfaz Runnable, incrementa la barra progreso
   */  
    
  /* class Hilo implements Runnable{
       public Thread thr;
       
       public Hilo(){
           thr = new Thread( this ) ;
       }*/
        /**
        * Metodo run de la hebra que es invocado cuando se llama al metodo start del objeto hebra declarado
        */
        @Override
        public void run() {
            for(int x=0;x<100;x++){
                barra.setValue(x);
                barra.repaint();
            
            try{
                Thread.sleep(100);
            }catch(Exception e){
            }
            }
        }
        
  //  }
    
    /**
 * Clase manejadora de eventos, usado para actualizar botones
 */
    class ManejadorAudio implements LineListener {
@Override

public void update(LineEvent event) {
    if (event.getType() == LineEvent.Type.START) {
        //VentanaInternaReproductor.this.botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayDisabled_48x48.png")));
        //VentanaInternaReproductor.this.botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48")));
       // if(player!=null) player.play();
        //botonPlayPause.setEnabled(false);
       // botonStop.setEnabled(true);
    }
    if (event.getType() == LineEvent.Type.STOP) {
        //VentanaInternaReproductor.this.botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48")));
        //VentanaInternaReproductor.this.botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48")));
       // if(player!=null) player.stop();
         VentanaInternaReproductorHebra.this.botonStop.setSelected(true);
        //botonPlayPause.setEnabled(true);
        //botonStop.setEnabled(false);
     }
    if (event.getType() == LineEvent.Type.CLOSE) {
       if (player != null) {
            player.stop();
    }
    if(event.getType() == LineEvent.Type.OPEN){
        //botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48")));
        //botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48")));
       // botonPlayPause.setEnabled(true);
        //botonStop.setEnabled(false);
        VentanaInternaReproductorHebra.this.botonStop.setSelected(true);
    }
}

        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPlayPause = new javax.swing.JToggleButton();
        botonStop = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        barra = new javax.swing.JProgressBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 70));

        botonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48.png"))); // NOI18N
        botonPlayPause.setToolTipText("Play");
        botonPlayPause.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayPressed_48x48.png"))); // NOI18N
        botonPlayPause.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/PlayDisabled_48x48.png"))); // NOI18N
        botonPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayPauseActionPerformed(evt);
            }
        });

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48.png"))); // NOI18N
        botonStop.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopPressedBlue_48x48.png"))); // NOI18N
        botonStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopNormalRed_48x48.png"))); // NOI18N
        botonStop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica10/StopDisabled_48x48.png"))); // NOI18N
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(botonPlayPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonStop)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPlayPause, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonStop, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Recoge evento e inicia reproduccion
 * @param evt ActionEvent
 */
    private void botonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayPauseActionPerformed
        if(player!=null){
            player.play();
            
            //new Thread(new Hilo()).start();
            
            if(runner==null){
                runner = new Thread(this);
                runner.start();
                /*runner=new Hilo();
                runner.thr.start();*/
            }else{
                runner.resume();
                
            //    runner.thr.resume();
                

                
            }
            
        }
        
    }//GEN-LAST:event_botonPlayPauseActionPerformed
/**
     * Recoge evento y para o corta reproduccion
     * @param evt ActionEvent
     */
    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        if(player!=null) player.stop();
        //if(runner.thr.isAlive()){
        if(runner.isAlive()){
            //runner.thr.suspend();
            runner.suspend();
            runner=null;
            barra.setValue(0);
            //runner.thr.destroy();
            
                   
        }
        //mejor destroy de la hebra ya que no es pause sino stop
    }//GEN-LAST:event_botonStopActionPerformed
/**
 * Recoge evento de cerrar ventana y para reproduccion
 * @param evt InternalFrameEvent
 */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (this.player != null) {
            this.player.stop();
    }
        //if(runner.isAlive()) runner.destroy();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JToggleButton botonPlayPause;
    private javax.swing.JToggleButton botonStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
