/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.fgm.iu;

import java.awt.BasicStroke;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Stroke;
import java.awt.image.BufferedImage;

/**
 *Clase que hereda de Lienzo2Dfinal , es la que usa VentanaInterna y permite cargar imagen de fondo
 * @author javi
 */
public class Lienzo2DImagenfinal extends Lienzo2Dfinal{
    BufferedImage img;
    private boolean ponerRecuadro = true;
/**
 * Devuelve si hay que poner marco
 * @return boolean
 */
    public boolean isPonerRecuadro() {
        return ponerRecuadro;
    }
/**
 * Establece si hay que poner marco
 * 
 * @param ponerRecuadro  boolean
 */
    public void setPonerRecuadro(boolean ponerRecuadro) {
        this.ponerRecuadro = ponerRecuadro;
    }
/**
 * Devuelve una imagen
 * @return BufferedImage
 */
    public BufferedImage getImage() {
        return img;
    }
/**
 * Crea el rectangulo ( para el lienzo ) con las dimensiones de la imagen y establece su correspondiente clip
 * @param img BufferedImage
 */
    public void setImage(BufferedImage img) {
        this.img = img;
        if(img!=null) {
           setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));//el scroll hay que ponerlo posicion centro           
           Rectangle r = new Rectangle(0, 0, img.getWidth(), img.getHeight());
           setClip(r);
}
    }

 /**
  * Devuelve imagen creategraphics del mismo tamaño que puede ser usads para dibujar si la booleana es true sino
  * devuelve la imagen 
  * @param drawVector boolean
  * @return BufferedImage
  * 
  */   
    public BufferedImage getImage(boolean drawVector){ 
        if (drawVector) {
             BufferedImage imgSal = new BufferedImage(this.img.getWidth(), this.img.getHeight(), this.img.getType());//se indica ancho alto y tipo
             paint(imgSal.createGraphics());
             return imgSal;
        }
        else{    
            return this.getImage();}
      
    }
    
  /**
   * La implementación por defecto del método paint de la clase JComponent llama, en este orden, a los métodos paintComponent, paintBorder y paintChildren. El primero de ellos es el que contiene el código que determina cómo se pinta el componente (los otros dos pintan el borde y llaman recursivamente al paint de los componentes/contenedores hijos).
   * @param g Graphics
   */  
    public void paintComponent(Graphics g){
        super.paintComponent(g);//llama al paint de lienzo2D el padre
        if(img!=null) g.drawImage(img,0,0,this);//leer pie de pagina se pone asi para que lo que se dibuje se vea sino se supondria si se sobrecargase paint
//el for de shape y se va pintando es lo siguiente que iria, se podria meter todo lo que va despues de la llamada a super.paint(g)
// en un metodo pintavectordeshape() y llamarse desde aqui , en vez de hacer for se llama pintavector justo despues del g.drawimage
        if ((this.clip != null) && (this.ponerRecuadro)) {
                ponerRecuadro(g);
         }
    }
   /**
    * Pinta el recuadro o clip en modo discontinuo para saber limite de donde se puede pintar
    * @param g Graphics
    */ 
    private void ponerRecuadro(Graphics g)
  {
    Graphics2D g2d = (Graphics2D)g;
    Stroke sk = g2d.getStroke();
    float[] patronDiscontinuidad = { 5.0F, 5.0F };
    Stroke linea = new BasicStroke(1.0F, BasicStroke.CAP_ROUND, BasicStroke.JOIN_MITER, 1.0F, patronDiscontinuidad, 0.0F);
    g2d.setStroke(linea);
    g2d.draw(this.clip);
    g2d.setStroke(sk);
  }
    /**
     * Constructor
     * Creates new form Lienzo2DImagen
     */
    public Lienzo2DImagenfinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration 
    
}
